global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'golang-app'
    static_configs:
      - ltargets: ['192.168.1.11:2112']
